version: "3.3"

services:

  samba4-dc:
    build: .
    image: "samba4-dc:latest"
    hostname: samba4-dc
    restart: always
    container_name: "samba4-dc"
    privileged: true
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - DOMAIN=xms.local
      - DOMAINPASS=mypassword
      - HOSTIP=192.168.2.8
      - INSECURELDAP=true
    ports:
      - "53:53"
      - "53:53/udp"
      - "88:88"
      - "88:88/udp"
      - "135:135"
      - "137-138:137-138/udp"
      - "139:139"
      - "389:389"
      - "389:389/udp"
      - "445:445"
      - "464:464"
      - "464:464/udp"
      - "636:636"
      - "1024-1044:1024-1044"
      - "3268-3269:3268-3269"
    networks:
      mynetwork:
        aliases:
          - samba4-dc
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/:/var/lib/samba"
      - "./config/samba:/etc/samba/external"
networks:
  mynetwork:
    external:
     name: mynetwork
